#!/bin/gawk
# awk --re-interval -f lrq/lrq-maeshori.awk skills.txt

!/^-------.+/{
    gsub(/;/, ":", $1)
    converted=gensub(/(判定|上限|タイミング|対象|射程|目標値|対決|購|携|攻|射|部位|解説|心\))('|1|二|ニ|=)/, "\\1:", "g", $1)
    converted=gensub(/(判定|上限|タイミング|対象|射程|目標値|対決|購|携|攻|射|部位):(ー|一)/, "\\1:-", "g", converted)
    converted=gensub(/(\/)(ー|一)/, "\\1-", "g", converted)
    gsub(/ァウ/, "アウ", converted)
    gsub(/イ三/, "イミ", converted)
    gsub(/ァク/, "アク", converted)
    gsub(/タ一/, "ター", converted)
    gsub(/ひとっ/, "ひとつ", converted)
    gsub(/→/, "ー〉", converted)
    gsub(/パり/, "パリ", converted)
    gsub(/白身/, "自身", converted)
    gsub(/自兵/, "白兵", converted)
    gsub(/白我/, "自我", converted)
    gsub(/言標/, "目標", converted)
    gsub(/ニシァ/, "ニシア", converted)
    gsub(/ス一/, "スー", converted)
    gsub(/リ一/, "リー", converted)
    gsub(/一ド/, "ード", converted)
    gsub(/一ト/, "ート", converted)
    gsub(/-一/, "-1", converted)
    gsub(/-方/, "一方", converted)
    gsub(/トり/, "トリ", converted)
    gsub(/フエ/, "フェ", converted)
    gsub(/ム工/, "ムエ", converted)
    gsub(/八イ/, "ハイ", converted)
    gsub(/力一/, "力ー", converted)
    gsub(/ベル:i/, "ベル:1", converted)
    gsub(/力ー/, "カー", converted)
    gsub(/一レベ/, "ーレベ", converted)
    gsub(/ジャ一/, "ジャー", converted)
    gsub(/ジヤ一/, "ジャー", converted)
    gsub(/二ュ/, "ニュ", converted)
    gsub(/二ユ/, "ニュ", converted)
    gsub(/二ュ一/, "ニュー", converted)
    gsub(/1ノ/, "レ", converted)
    gsub(/力ブ/, "カブ", converted)
    gsub(/力ッ/, "カッ", converted)
    gsub(/力レ/, "カレ", converted)
    gsub(/ガ一/, "ガー", converted)
    gsub(/メ一/, "メー", converted)
    gsub(/ェン/, "エン", converted)
    gsub(/ァップ/, "アップ", converted)
    gsub(/りア/, "リア", converted)
    gsub(/ィァ/, "ィア", converted)
    gsub(/ェキス/, "エキス", converted)
    gsub(/工キス/, "エキス", converted)
    gsub(/÷\[/, "÷[", converted)
    gsub(/i回/, "1回", converted)
    gsub(/\+I/, "+1", converted)
    gsub(/\+i/, "+1", converted)
    gsub(/1J/, "1]", converted)
    gsub(/【AR./, "【AR】", converted)
    gsub(/\[レベル】/, "[レベル]", converted)
    gsub(/がO/, "が0", converted)
    gsub(/がO/, "が0", converted)
    gsub(/1O/, "10", converted)
    gsub(/1O/, "10", converted)
    gsub(/ー\[/, "-[", converted)
    gsub(/一\[/, "-[", converted)
    gsub(/一1/, "-1", converted)
    gsub(/一2/, "-2", converted)
    gsub(/一3/, "-3", converted)

    #gsub(/^判定:/, "@\n判定:", converted)
    #gsub(/^(判定|購):/, "@\n判定:", converted)
    converted=gensub(/^(判定|購):/, "@\n\\1:", "g", converted)

    print converted
}
